# Generated by Django 3.2.7 on 2021-12-21 07:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211220_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dated_posted',
            field=models.DateField(default=datetime.datetime(2021, 12, 21, 7, 26, 2, 490998, tzinfo=utc)),
        ),
    ]
